name: CommandCanceler
main: net.testusuke.open.CommandCanceler.Main
version: 1.0
author: testusuke
description: this plugin is able to cancel disallow Commands,and execute command when execute disallow commands.
commands:
  cc:
    permission: commandcanceler.admin